services:
  - type: web
    name: tarun-portfolio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: FLASK_APP
        value: "main.py"
      - key: FLASK_ENV
        value: "production"
